# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.4
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
      - name: test
        run: |
          yarn install
          yarn test:jcov
      - name: gen_cov
        run: |
          bash <(curl -s https://codecov.io/bash)
#           set -x
#           COVERAGE_PERCENT=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
#           if (( $(echo "$total <= 50" | bc -l) )) ; then
#             COLOR=red
#           elif (( $(echo "$total > 80" | bc -l) )); then
#             COLOR=green
#           else
#             COLOR=orange
#           fi
          
            

#          curl "https://img.shields.io/badge/coverage-COVERAGE_PERCENT%25-$COLOR" > badge.svg



